### PR TITLE
adding more features

### PR DESCRIPTION
**Pull request by y0y0z**
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy

### CODE REVIEW

**Comment by y0y0z** [comment]
@EvanHahn: i can do that, same as you can :) but please share why do you want to revert these changes

**Comment by EvanHahn** [comment]
This is a pull request to add additional features. I'd like to avoid making unrelated changes, such as updating test coverage.

**Comment by EvanHahn** [comment]
I've updated all dependencies to their latest versions, so it could be worth merging/rebasing `master`.

**Comment by y0y0z** [comment]
@EvanHahn: done. :shipit:

**Comment by EvanHahn** [comment]
Thanks! This has been deployed in `feature-policy@0.5.0`.

Feel free to add yourself to [the contributors list](https://github.com/helmetjs/helmetjs.github.io/blob/master/contributors/index.md).

**Pull request merged**
